# Generated by Django 2.0.6 on 2018-06-19 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(0, 'Not a member'), (1, 'Member'), (2, 'President'), (3, 'Financial Director'), (4, 'Technology Director'), (5, 'Marketing Director'), (6, 'Deliberative Council'), (7, 'Fiscal Council'), (8, 'Alternate')], default=0)),
                ('github_username', models.CharField(blank=True, max_length=39)),
                ('thumbnail_url', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
